---
name: Cordova Docker Action
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Docker
        uses: docker://docker:19.03.13
      - name: create container from image named we2app/cordova
        run: docker run -i -v $(pwd):/app --name cordova we2app/cordova sh -c "cd /app
          && export ANDROID_HOME=/opt/android-sdk && export
          ANDROID_SDK_ROOT=/opt/android-sdk && export
          PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin/:$ANDROID_HOME/platform-tools
          && ls && cordova platform add android && cordova build android"
      - name: Release
        uses: softprops/action-gh-release@
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /platforms/android/app/build/outputs/apk/debug/app-debug.apk