name: Example Docker Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker
      uses: docker://docker:19.03.13

    # - name: Run command
    #   run: docker run --rm -v "$PWD":/app -w /app we2app/cordova:latest sh -c "echo 'Hello, GitHub Actions in Docker!'"

    - name: create container from image named we2app/cordova
      run: docker create --name cordova we2app/cordova:latest

    - name: Copy current code to container
      run: docker cp . cordova:/app

    - name: Run build
      run: docker start -a cordova sh -c "cordova -v && cordova add platform android && cordova build android"

    # - name: Copy build to current code
    #   run: docker cp we2app/cordova:/app/platforms/android/app/build/outputs/apk/debug/app-debug.apk .

    # - name: Upload build to artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: app-debug.apk
    #     path: app-debug.apk

    # - name: Upload build to release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: app-debug.apk